In [66]:
import numpy as np

# create an array with desired values
np_arr = np.array([[1,2],[3,4]])

np_arr.T

array([[1, 3],
       [2, 4]])

In [11]:
# create an array of desired shape initiated with value zero
np_arr_zeros = np.zeros((3,4))
np_arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# create an array of desired shape initiated with value one
np_arr_ones = np.ones((3,4))
np_arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# reshape an array with new given shape, sizes should be compatible to reshape an array
np_reshape_Arr_1 = np.reshape(np_arr_ones, (4,3))
np_reshape_Arr_2 = np.reshape(np_arr_ones, (2,6))
np_reshape_Arr_1, np_reshape_Arr_2

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]))

In [24]:
# Join a sequence of arrays on the given axis
a1 = np.zeros((3,3))
a2 = np.ones((2,3))
np.concatenate((a1, a2), axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# calculate the mean of all the elements of an array if no axis parameter given, else calculate the mean along the given axis
arr = np.array([[1,2],[3,4]])
np.mean(arr, axis=1)

array([1.5, 3.5])

In [37]:
# calculate the sum of all the elements of an array
a1 = np.ones((3,3))
np.sum((a1))

9.0

In [40]:
# calculate the minimum value among all the elements of an array
a1 = np.array([[1,2], [3,4], [0.5,2.5]])
np.min(a1)

0.5

In [39]:
# calculate the maximum value among all the elements of an array
a1 = np.array([[1,2], [3,4], [0.5,2.5]])
np.max(a1)

4.0

In [43]:
# calculate the index of maximum value among all the elements of an array along the given axis
a1 = np.array([[1,2], [3,4], [0.5,2.5]])
np.argmax(a1, axis=1), np.argmax(a1, axis=0)

(array([1, 1, 1]), array([1, 1]))

In [44]:
# calculate the index of minimum value among all the elements of an array along the given axis
a1 = np.array([[1,2], [3,4], [0.5,2.5]])
np.argmin(a1, axis=1), np.argmin(a1, axis=0)

(array([0, 0, 0]), array([2, 0]))

In [45]:
# returns random values in a given shape
np_arr_rand = np.random.rand(2,4)
np_arr_rand

array([[0.48279794, 0.09468882, 0.04493733, 0.40840599],
       [0.21763558, 0.65780483, 0.48670763, 0.65496877]])

In [49]:
# creates an array filled with random values as per standard normal distribution in a given shape
np_arr_randn = np.random.randn(2,4)
np_arr_randn

array([[-1.09717731, -1.11513581,  0.31510068,  0.624703  ],
       [ 0.42636562,  0.35106601,  0.09673749,  1.53350859]])

In [70]:
# creates an array filled with integer values from start to end value in the given shape/size
np_arr_randint = np.random.randint(1,17, size=(2,3))
np_arr_randint

array([[ 4, 10,  6],
       [ 8, 15,  1]])

In [73]:
# Dot product of two array under condition that last dimension in a1 is equal to second to last dimension of a2
a1 = np.random.randint(2,4, size=(2,4,1))
a2 = np.random.randint(1,2, size=(4,1,2))
a1, a2, np.dot(a1, a2)

(array([[[3],
         [3],
         [3],
         [3]],
 
        [[3],
         [3],
         [3],
         [2]]]),
 array([[[1, 1]],
 
        [[1, 1]],
 
        [[1, 1]],
 
        [[1, 1]]]),
 array([[[[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]],
 
         [[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]],
 
         [[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]],
 
         [[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]]],
 
 
        [[[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]],
 
         [[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]],
 
         [[3, 3],
          [3, 3],
          [3, 3],
          [3, 3]],
 
         [[2, 2],
          [2, 2],
          [2, 2],
          [2, 2]]]]))